update env
1. auto resolving jdk and boost dependency on Ubuntu 16.04
2. never rely on this for running, it is just a helper for resolving
dependencies

diff --git a/resources/env b/resources/env
--- a/resources/env
+++ b/resources/env
@@ -1,32 +1,84 @@
 #!/bin/bash
 
+PWD=`pwd`
+BOOST_TAR="boost_1_65_1.tar.bz2"
+BOOST_SHA1SUM=4a5b0c3c1b1b9a4d6cb6a6cc395e903e76f76720
+JDK_TAR="openjdk-11.0.1_linux-x64_bin.tar.gz"
+JDK_SHA1SUM=2737d3c1c67d5629383d6da4c4c33b1e3427c3d6
+
 ## Step 0: check system version
 USERNAME=`whoami`
 echo -e "\033[32mHello $USERNAME, welcome to Aion Rust Kernel \033[0m"
+apt install -y lsb-release wget bzip2 gawk
 
-if [ ! -f "custom.env" ];then
-    echo -e "\033[33mWARN: Seems this is your first time to run Aion Rust Kernel, resolving dependencies \033[0m"
-    SYSINFO=`uname -a | sed -n '/18.04.*-Ubuntu/p'`
-    if [ -n "$SYSINFO" ];then
-        echo "Found Ubuntu 18.04" 
-    else
-        echo -e "\033[33mWARN: Not Official Support Version \033[0m"
-    fi
-
+function resolve_u1804 {
     ## Step 1: check java environment
     if [ -z "$JAVA_HOME" ];then
         echo -e "\033[33mWARN: JAVA_HOME not found, try to install jdk first \033[0m"
-        sudo apt install -y openjdk-11-jdk
+        apt install -y openjdk-11-jdk
         echo "export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64" > ./custom.env
         echo -e "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$JAVA_HOME/lib/server" >> ./custom.env
     fi
 
     touch ./custom.env
+    
     ## Step 2: install dependencies
     echo -e "\033[33mupdating repositories\033[0m"
-    sudo apt update 2> /dev/null 1>&2
+    apt update 2> /dev/null 1>&2
     echo -e "\033[33minstalling local dependencies\033[0m"
-    sudo apt install -y libboost-filesystem1.65-dev libboost-program-options1.65-dev llvm-4.0-dev 1> /dev/null 2>&1
+    apt install -y libboost-filesystem1.65-dev libboost-program-options1.65-dev llvm-4.0-dev 1> /dev/null 2>&1
+}
+
+function resolve_u1604 {
+    if [ -z "$JAVA_HOME" ];then
+        # Download jdk 11
+        if [ ! -f "$JDK_TAR" -o "`sha1sum $JDK_TAR | awk '{print$1}'`" != "$JDK_SHA1SUM" ]; then
+            wget https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
+            if [ `sha1sum $JDK_TAR != $JDK_SHA1SUM` ];then
+                echo "Download openjdk failed"
+                exit -1
+            fi
+        fi
+
+        mkdir jdk
+        tar xvf openjdk-11.0.1_linux-x64_bin.tar.gz -C jdk
+        echo "export JAVA_HOME=$PWD/jdk/jdk-11.0.1" > ./custom.env
+        echo -e "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$JAVA_HOME/lib/server" >> ./custom.env
+
+        ## install boost
+        if [ ! -f "$BOOST_TAR" -o "`sha1sum $BOOST_TAR | awk '{print$1}'`" != "$BOOST_SHA1SUM" ]; then
+            wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
+            if [ `sha1sum $BOOST_TAR != $BOOST_SHA1SUM` ];then
+                echo "Download boost failed"
+                exit -1
+            fi
+        fi
+        sudo apt -y install gcc g++
+        tar xvf boost_1_65_1.tar.bz2
+        cd boost_1_65_1
+        ./bootstrap.sh --libdir=/usr/lib/x86_64-linux-gnu/
+        ./b2
+        ./b2 install
+    fi
+
+    ## install llvm-4.0
+    apt -y install libllvm4.0
+}
+
+if [ ! -f "custom.env" ];then
+    echo -e "\033[33mWARN: Seems this is your first time to run Aion Rust Kernel, resolving dependencies \033[0m"
+    SYSINFO=`lsb_release -r | awk '{print$2}'`
+    if [ "$SYSINFO" == "18.04" ];then
+        echo "Found Ubuntu 18.04" 
+        resolve_u1804
+    elif [ "$SYSINFO" == "16.04" ];then
+        echo "Found Ubuntu 16.04"
+        resolve_u1604
+    else
+        echo -e "\033[33mWARN: Not Official Support Version \033[0m"
+    fi
+
+    
 fi
 
 echo -e "\033[32mCongratulations! Aion Rust Kernel is ready to run\033[0m"
